#+TITLE: Development for KanripoX
#+AUTHOR: Christian Wittern
#+DATE: 2020-04-11

* Overview

  KanripoX is the next generation format for the Kanseki Repository.
  It combines the previous experiences with various encoding
  standards, text collections, philological methods and user
  requirements into a collection of texts, related data and tools.
  
  It thus draws freely from existing material, where possible
  acknowledging the debt.  Apologies in advance if this at times has
  not been actualized, any oversight is not intentional.

* Anatomy of a text repository

  Individual texts have all information bundled in a repository, just
  as in the Kanseki repository.  All versions and all related
  information is in the same branch, thus always visible and
  accessable (at least in theory, but maybe not in practice, as the
  information might reside somewhere else and/or has usage
  restrictions).  The specifics are quite variable and detailed in the
  =Manifext.xml=, which is one of the required files.

** Textual sources

   Textual sources are treated slightly different depending on their status as
   *documentary* or *interpretative*. Apart from that, they are treated the
   same.

   Text content might be encoded in XML using the TEI Guidelines, or in the
   Mandoku text format of the Kanseki Repository. Processing for additional
   formats might be added in the future.

   In the case of a XML file, the text content is distributed across several
    files, usually one file for a smaller unit of the text, such as a /juan/ or
    /booklet/, in the same way this is done in the Mandoku format of the Kanseki
    Repository. These files are put into subfolders according to the edition
    they belong to, a parent XML files includes all of them into one virtual
    document (using XInclude). -> for other files use alignment table that
    indicates were to split.

    The language of the texts in the Kanseki Repository in general will be
    "Literary Chinese", for which the ISO 639-3 language code is lzh. For other
    languages, the identifiers should be used as fitting.

    Machine readable identifiers for the text should be derived from
    their status and editions, eg. KR3a0007_SBCK, KR3a0007_tls-en ->
    Edition labels (SBCK, master, tls-en) can not include "_" and need
    to be unique across all files. Identifiers within the text can be
    unique to that text only.
    

*** Documentary files (=doc=)

    Documentary files document a specific edition, usually a print edition. It
    can exist as a transcription, a digital facsimile or a combination of both.
    The XML files for this are prepared according to the TEI Guidelines.

*** Interpretative files (=int=)

    Versions of the text that are not intended to directly replicate an existing
    version, but rather derive from such a version, for example by normalizing
    character representation, translation (published translations that are
    reproduced as such, without editorial intervention, should go into the
    documentary section), punctuation etc.

*** Commentaries (=com=)

Other derived texts, summaries etc. will go here. Or put these into the above categories?

** Auxiliary files (=aux=)

   These are files that are required or useful for making use of the
   the text files.  They include machine readable lists of text
   tokens, link lists that are used to align the various versions of a
   text and other types of annotations, some might be algorithmically
   derived from the texts, others hand-crafted.
*** Structural divisions (=div=)
The structural divisions link an abstract notion of the divisions (books,
chapters, sections) in a work to the addressable, machine readable locations in
a file. At the same time, they also serve to structurally align the different
texts at an abstract level.
*** Link Lists (=lnk=)

    Various types:
    - corresponding sections of text
      - within this text, but also with other texts
    - link text to commentary
    - link text to translation
    - logical structure
    - virtual anthology, excerpts
   
**** Alignment tables:
For every file, we will produce a file that contains the token alignments for
all the other files, based on the ID unit of the file, this will currently
either be <line> or <seq>, while alignments on larger units like paragraphs do
not work very well.
#+begin_example language=xml
<seg id='CH1a0907_CHANT_001-4a.34' tp='462' tcount='5'>
<ref ed='KR3a0007_SBCK' corresp='#KR3a0007_SBCK_001-2b.08' tp='1157' tcount='4' diff='1'/>
<ref ed='KR3a0007_WYG' corresp='#KR3a0007_WYG_001-2b.03' tp='1498' tcount='4' diff='1'/>
<ref ed='KR3a0007_master' corresp='#KR3a0007_master_001' tp='1157' tcount='4' diff='1'/>
</seg>
<seg id='CH1a0907_CHANT_001-4a.35' tp='467' tcount='2'>
<ref ed='KR3a0007_SBCK' corresp='#KR3a0007_SBCK_d' tp='0' tcount='0' diff='2'/>
<ref ed='KR3a0007_WYG' corresp='#KR3a0007_WYG_d' tp='0' tcount='0' diff='2'/>
<ref ed='KR3a0007_master' corresp='#KR3a0007_master_d' tp='0' tcount='0' diff='2'/>
</seg>
<seg id='CH1a0907_CHANT_001-4a.36' tp='469' tcount='9'>
<ref ed='KR3a0007_SBCK' corresp='#KR3a0007_SBCK_001-2b.09' tp='1161' tcount='8' diff='1'/>
<ref ed='KR3a0007_WYG' corresp='#KR3a0007_WYG_001-2b.03' tp='1502' tcount='8' diff='1'/>
<ref ed='KR3a0007_master' corresp='#KR3a0007_master_001' tp='1161' tcount='8' diff='1'/>
</seg>
#+end_example

In the second example, the corresponding segment in the other texts is
completely missing, therefore there is no link possible to a corresponding
section in these texts. For the sake of processing with collatex, we introduce a
dummy ID here, identified with 'd' (for deleted) in place of the text location.

*** Syntactic Word Locations (=swl=)

Annotations from the TLS project, according to the format used there.

*** Collatex tokens (=tok=)

Tokenized versions of the XML files, in a format suitable to be fed to CollateX.
These are required to produce the alignment tables.
#+begin_example lang=xml
<div>[...]
   <t tp="468" id="CH1a0907_CHANT_001-4a.35" el="p seg" pos="1">言</t>
   <t tp="469"
      f="，"
      id="CH1a0907_CHANT_001-4a.35"
      el="p seg"
      pos="2">行</t>
   <t tp="470" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="1">君</t>
   <t tp="471" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="2">子</t>
   <t tp="472" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="3">之</t>
   <t tp="473" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="4">所</t>
   <t tp="474" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="5">以</t>
   <t tp="475" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="6">動</t>
   <t tp="476" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="7">天</t>
   <t tp="477" id="CH1a0907_CHANT_001-4a.36" el="p seg" pos="8">地</t>
   <t tp="478"
      f="，"
      id="CH1a0907_CHANT_001-4a.36"
      el="p seg"
      pos="9">也</t>
   <t tp="479" id="CH1a0907_CHANT_001-4a.37" el="p seg" pos="1">可</t>
   <t tp="480" id="CH1a0907_CHANT_001-4a.37" el="p seg" pos="2">不</t>
   <t tp="481" id="CH1a0907_CHANT_001-4a.37" el="p seg" pos="3">慎</t>
   <t tp="482"
      f="！』"
      id="CH1a0907_CHANT_001-4a.37"
      el="p seg"
      pos="4">乎</t>
[...]
</div>
#+end_example

* Ideas

  - mark one edition as "pivot", this will be the one with segments marked.
